### ISSUE TITLE
Typo3 10.4 site identifier "main"

### ISSUE THREAD

**Issue by okroener** [sourcebroker/t3api#10]
t3api\Classes\Dispatcher\Bootstrap.php

`->getSiteByIdentifier('main')`

May be this could be added to the documentation, that the site identifier has to be called "main". I have been struggling with that in Typo3 10.4 ... but somehow not in 9.5.x?

**Comment by klamparski** [comment]
@okroener Thanks for pointing it out. I will check and implement better solution or at least mention about that in documentation.

**Comment by Moongazer** [comment]
Just stumbled about the same issue. Do you think the site-identifier could be stored in a configuration value? Not sure where it makes most sense, in TypoScript or in a global extension-configuration (BE => Settings => Extension Configuration). If no configuration is given, it could fall back to 'main'.

**Comment by sourcebrokergit** [comment]
Fixed in 1.0.6.

**Comment by kszymukowicz** [comment]
Fixed in 1.0.6.
