### ISSUE TITLE
[BUG] CurrentFeUserSubscriber throws warning at virtual properties

### ISSUE THREAD

**Issue by Idleworks** [sourcebroker/t3api#100]
### TYPO3 version

12.4.20

### PHP version

8.3.11

### Extension version

3.0.2

### Composer mode

- [X] I'm running TYPO3 in composer mode.

### Operating system

Ubuntu 12.04 on WSL

### Current behavior

CRUD operations on FrontendUser with virtual properties (@T3api\Serializer\VirtualProperty()) throws php warning and returns HTTP 500:

> PHP Warning: Trying to access array offset on null in /var/www/html/vendor/sourcebroker/t3api/Classes/Serializer/Subscriber/CurrentFeUserSubscriber.php line 58

### Expected behavior

CRUD operation returns HTTP 200 with no php warnings.

### Steps to reproduce

Add FrontendUser Model with an api endpoint annotation, any virtual property and a relational model referencing back to FrontendUser having CurrentFeUserSubscriber. 

E.g. 

FrontendUser
 - myVirtualProperty
 - relationProperty
- - relationModel
- - - frontendUser

### Additional context

Virtual properties do not have "type" property in metadata and that's why a warning is raised in CurrentFeUserSubscriber which will break functionality on productional environments.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by kszymukowicz** [comment]
Tnx!
Released in [3.0.5](https://github.com/sourcebroker/t3api/releases/tag/3.0.5)
