### ISSUE TITLE
A place to put the business logic

### ISSUE THREAD

**Issue by Moongazer** [sourcebroker/t3api#12]
Not sure if this is an issue, but as far as I can see only classes which extend Extbase's `AbstractDomainObject` can deliver content over the API. That makes me wonder how or where to define business logic (the model should not contain such, right?).

As example, lets say I need to have an endpoint which receives a complex setting-object. The settings are stored in multiple tables, so usually a controller or service has do handle this. Another usecase is how to make aggregated/calculated database values available? Like a statistic-endpoint which gives back aggregated values based on a custom SQL query using SUM/AVG functions (logic from a repository).

I took a look to the `t3apinews` example, but could not find any logic there. Can `t3api` handle such cases or is it not made for it (yet)?

**Comment by kszymukowicz** [comment]
Support for custom endpoints with own controller is already done in branch https://github.com/sourcebroker/t3api/tree/issue-7 but needs to be yet rechecked before merging to master.

In short you need to register handler in ext_localconf.php

```
$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['t3api']['operationHandlers'][\V\Myext\OperationHandler\Operation1Handler::class] = 100;
$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['t3api']['operationHandlers'][\V\Myext\OperationHandler\Operation2Handler::class] = 100;
```
The `100` is priority if there is more implementation of the same endpoint.

Then create a model for business logic (in this model you will define possible endpoints with annotations)
(`Classes/Domain/Model/Logic1.php`)

```
/**
 *
 * @T3api\ApiResource (
 *     itemOperations={
 *          "operation1"={
 *              "path"="/logic1/something1",
 *              "method"="GET",
 *          },
 *          "operation2"={
 *              "path"="/logic1/something2",
 *              "method"="GET",
 *          }
 *     }
 * )
 */
class Logic1 extends \TYPO3\CMS\Extbase\DomainObject\AbstractEntity
{

}
```

And then implement handler itself like in this example:

```
class Operation1Handler implements OperationHandlerInterface
{
    public static function supports(OperationInterface $operation, Request $request): bool
    {
        return $operation->getApiResource()->getEntity() === Logic1::class 
                     && $operation->getKey() === 'operation1';
    }

    /**
     * @inheritDoc
     * @throws \Exception
     */
    public function handle(OperationInterface $operation, Request $request, array $route, ?ResponseInterface &$response)
    {
        // logic here
        // ...

        return [
            'result' => 'success'
        ];
    }
}
```

```
class Operation2Handler implements OperationHandlerInterface
{
    public static function supports(OperationInterface $operation, Request $request): bool
    {
        return $operation->getApiResource()->getEntity() === Logic1::class 
                     && $operation->getKey() === 'operation2';
    }

    /**
     * @inheritDoc
     * @throws \Exception
     */
    public function handle(OperationInterface $operation, Request $request, array $route, ?ResponseInterface &$response)
    {
        // logic here
        // ...

        return [
            'result' => 'success'
        ];
    }
}
```
