### ISSUE TITLE
[BUG] pid serialization error

### ISSUE THREAD

**Issue by jackd248** [sourcebroker/t3api#122]
### TYPO3 version

13.4.0

### PHP version

8.3.12

### Extension version

4.02

### Composer mode

- [X] I'm running TYPO3 in composer mode.

### Operating system

macOS 15.0.1

### Current behavior

Hej,
I was trying to manage an simple extbase model via the api with POST and PATCH, but always getting the serializer error:

```
Expected argument of type \"int\", \"null\" given at property path \"pid\".
```

I'm not sure why the serializer didn't realize, that the pid is nullable. 
Here is my according annotation:

```php
/**
 * @ApiResource(
 *     collectionOperations={
 *         "get": {
 *             "path": "/items",
 *         },
 *         "post": {
 *             "path": "/items",
 *             "method": "POST",
 *         },
 *     },
 *     itemOperations={
 *         "get": {
 *             "path": "/items/{id}",
 *         },
 *         "patch": {
 *             "path": "/items/{id}",
 *             "method": "PATCH",
 *         },
 *         "delete": {
 *             "path": "/items/{id}",
 *             "method": "DELETE",
 *         }
 *     },
 *     attributes={
 *         "persistence": {
 *             "storagePid"="2",
 *              "recursive"=1
 *         }
 *     }
 * )
 */
class Item extends AbstractEntity {...}
```

Do I miss some additional configuration?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by klamparski** [comment]
@jackd248 Didn't test it myself but I guess the point here is that `pid` setter is not nullable in `\TYPO3\CMS\Extbase\DomainObject\AbstractDomainObject`. Try to override the setter with nullable type inside `Item`.

```
public function setPid(?int $pid): void
    {
        $this->pid = $pid;
    }
```

**Comment by kszymukowicz** [comment]
@jackd248 

Please install local test instance.
1. Clone t3api to some separate folder.
2. `ddev composer i && ddev ci 13` 
3. Check folder `.test/13/src/t3apinews`. There is working model for ext:news which also do POST, PATCH.

With `ddev composer ci:tests:postman 13` you can test this endpoint.
Postman tests are in `Tests/Postman`.

**Comment by jackd248** [comment]
> I assumed you are sending pid in the payload (which is no required). I if you are not sending pid in the payload then this is not appropriate solution of course.

No, I'm not, that was confusing me. But you were right, adding an additional setter for the pid fixes the issue. 

But I don't understand why this is not a problem with every Extbase model? It doesn't seem to be necessary for the news test you linked to.

By the way, I'm still struggling with the wildcard hostname to get the test suite to work.

**Comment by kszymukowicz** [comment]
"By the way, I'm still struggling with the wildcard hostname to get the test suite to work."?

Strange. All is default ddev possibilities.

**Comment by klamparski** [comment]
> No, I'm not, that was confusing me. But you were right, adding an additional setter for the pid fixes the issue.
> But I don't understand why this is not a problem with every Extbase model? It doesn't seem to be necessary for the news test you linked to.

No, it's not the correct solution for sure - I assumed you are sending `pid: null` in the payload and that's why I suggested it.  If you don't do it then overriding the setter is definitely not a solution.

As a fast solution for you I think that you might try to use `groups` in `normalizationContext` (check how it is done in `t3apinews`). Generally it's imo preferred to use serialization groups always. It could also be that we don't even test scenario without such groups and that could be the reason of the issue you are facing now.

**Comment by jackd248** [comment]
> No, it's not the correct solution for sure - I assumed you are sending pid: null in the payload and that's why I suggested it. If you don't do it then overriding the setter is definitely not a solution.

I'm using your web api backend module to test the request and definitely not sending the pid:

```
curl -X 'POST' \
  'https://items.ddev.site/_api/items' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "title": "Test",
  "description": "Test"
}'
```

> As a fast solution for you I think that you might try to use groups in normalizationContext (check how it is done in t3apinews). Generally it's imo preferred to use serialization groups always. It could also be that we don't even test scenario without such groups and that could be the reason of the issue you are facing now.

Yes, thats the right guess. Working with the normalization groups fixes the problem for me. 

Thanks for your fast help, @klamparski  & @kszymukowicz

**Comment by kszymukowicz** [comment]
@jackd248 

It would be fine that you give me feedback about problems with this local instance at https://13.t3api.ddev.site/
I am interested what can be wrong here.
Better private as this is not main issue here.

**Comment by jackd248** [comment]
After a little research, i suspect a problem with my local ddev instance.

> DDEV cannot add unresolvable hostnames like `*.t3api.ddev.site` to your hosts file.

Wildcard hostnames only work with dns. Unfortunately my ddev uses the /etc/hosts instead, so `use_dns_when_possible` isn't working here.

https://ddev.com/blog/ddev-name-resolution-wildcards/

I have not yet found out the actual cause, but i think it can be summarised that wildcards do not work equally for all ddev installations.
