### ISSUE TITLE
API site-config entry other than "/" resulting in "RuntimeException: Route enhancer `T3apiResourceEnhancer` is not defined"

### ISSUE THREAD

**Issue by Moongazer** [sourcebroker/t3api#13]
If we have 2 root-pages (e.g. one for the website, another one for the API), with the "website" site-config entry defined as "/" (base URL) and the "api" site-config entry defined as "/v1", the following exception is thrown (backend and frontend):

**Route enhancer `T3apiResourceEnhancer` is not defined. You need to add it to your site configuration first. See example configuration in PHP doc of SourceBroker\T3api\Routing\Enhancer\ResourceEnhancer.**

**Comment by Moongazer** [comment]
Not 100% sure but I think I've found my mistake:
Site-1 config was on base `https://domain.net`
Site-2 config was on base `https://sub.domain.net` (here is where t3api should work)

If I login to the backend with `https://domain.net/typo3`, the above exception is thrown e.g. if I want to edit the root template of Site-2.

Not sure if I should close this issue because on one hand it's not really a bug, as the function `getSite()` does exactly what it should: it returns the site where I'm logged-in as (if it's the "wrong" URL, the "wrong" site comes back without `T3apiResourceEnhancer` config). On the other hand this is quite a trap, maybe this can be improved in a future version somehow.

**New workaround:** make sure to work under the right domain (`https://sub.domain.net/typo3` in this case).

**Comment by klamparski** [comment]
Fix for that issue is merged to master now. Will be included in version 1.1.1.

**Comment by Moongazer** [comment]
Just checked, the issue is gone using the current master, thanks.
