### ISSUE TITLE
Extension can't be installed without composer.

### ISSUE THREAD

**Issue by bioCTRL** [sourcebroker/t3api#15]
It's not possible to install the Extension via TYPO3 Backend > Extensions. The Vendor Files seems to be missing. Is there a solution for this problem?

**Comment by kszymukowicz** [comment]
We support only installation by composer.

**Comment by rafu1987** [comment]
@bioCTRL I created an extension to provide the composer packages and to run t3api without composer. Let me know if this works for you, as I faced the same problem in non-composer mode. :-)

https://git.gandayo.com/extensions/typo3/gg/ggt3api

**Comment by olek07** [comment]
@rafu1987 What is the sense to do this?

`$boot = function () {
    /** @var \Composer\Autoload\ClassLoader $loader */
    $loader = require \TYPO3\CMS\Core\Core\Environment::getPublicPath() . '/typo3conf/ext/ggt3api/vendor/autoload.php';
};

$boot();
unset($boot);`

A normal include also works for me. 
There is no method `\TYPO3\CMS\Core\Core\Environment::getPublicPath` in my TYPO3 8.7.32 installation.
