### ISSUE TITLE
Method `getPublicUrl` can return `null` within `\SourceBroker\T3api\Serializer\Handler\FileReferenceHandler::serialize`

### ISSUE THREAD

**Issue by websi** [sourcebroker/t3api#17]
At line 112 within class `\SourceBroker\T3api\Serializer\Handler\FileReferenceHandler` the PHP method `parse_url` can be called with `null` value.

These lead to an TypeError.

```
parse_url() expects parameter 1 to be string, null given

TypeError thrown in file
/var/www/vagrant/releases/20200923061840/typo3conf/ext/t3api/Classes/Serializer/Handler/FileReferenceHandler.php in line 113.
```

The public url is `null`, if file is missing in the system.

**Comment by kszymukowicz** [comment]
Fixed in v1.2.3.
