### ISSUE TITLE
Uncaught TYPO3 Exception: Return value of SourceBroker\T3api\Service\RouteService::getSite()

### ISSUE THREAD

**Issue by martin-git-kristensen** [sourcebroker/t3api#19]
My setup is: Typo3 9.5.22 with solr 11.0.3 and t3api 1.1.0
When I do a solr indexing job in the scheduler I get this error - but only if the t3api is installed and running:
Core: Exception handler (CLI): Uncaught TYPO3 Exception: Return value of SourceBroker\T3api\Service\RouteService::getSite() must be an instance of TYPO3\CMS\Core\Site\Entity\Site, null returned

I simply cant find what the problem is - can you help here?

![solr-indexing-fejl](https://user-images.githubusercontent.com/54167636/98237689-93fe3300-1f65-11eb-919e-fa2c3f106c0a.jpg)

**Comment by klamparski** [comment]
Thanks for reporting this issue @martin-git-kristensen . I'm already in the middle in implementation of fix for it. Will be included in new bugfix release until the end of this week. Will inform you in this thread when it is released.

**Comment by klamparski** [comment]
Fix for that issue is merged to master now. Will be included in version 1.1.1.

**Comment by martin-git-kristensen** [comment]
I can confirm that the error is gone by updating to master - THANKS a lot :-) Very nice :-)
