### ISSUE TITLE
Improve and refactor loader for API Resource classes

### ISSUE THREAD

**Issue by klamparski** [sourcebroker/t3api#22]
Currently path of API Resource classes is not configurable. There is hardcoded path `Classes/Domain/Model/*.php` of loaded extensions (see `\SourceBroker\T3api\Domain\Repository\ApiResourceRepository::getAllDomainModels`). Although it's probably enough for most of use cases, hardcoded part makes it impossible to write tests. This task is about refactoring this part of code to make it possible to write tests.
Moreover within this task t3api should start to include also subfolders of `Classes/Domain/Model` when looking for API Resources.

- [x] Make API Resource path configurable.
- [x] Include subfolders of `Classes/Domain/Model` when searching for API Resource.
- [x] Write unit/functional tests.
- [x] Write documentation how to customise API Resource path.

**Comment by TokeHerkild** [comment]
I'm testing it on TYPO3 10.4.21.
A few issues, its not overly fond of transient/protected/private values.
and when everything is cleaned up it fails on: 
_The property \"requestId\" on the subject does not exist._
