### ISSUE TITLE
Bug: Serializer TypolinkHandler can not handle absolute URLs

### ISSUE THREAD

**Issue by Moongazer** [sourcebroker/t3api#33]
If an absolute URL is set for a link-attribute like an external URL or mail-link, the `Classes/Serializer/Handler/TypolinkHandler.php` concatenates the current `TYPO3_SITE_URL` with the given (absolute) `$typolinkParameter`.

To fix it, I'd suggest to test the `$typolinkParameter` if it's a TYPO3 URN `t3://`, if not it is considered as absolute URL which does not need further processing:

```
    public function serialize(
        SerializationVisitorInterface $visitor,
        $typolinkParameter,
        array $type,
        SerializationContext $context
    ) {
        if (!empty($typolinkParameter) && !preg_match('/^t3:\/\/.*$/', $typolinkParameter)) {
            return $typolinkParameter;
        } else {
            return rtrim($context->getAttribute('TYPO3_SITE_URL'), '/') . $this->getContentObjectRenderer()->getTypoLink_URL(...(array)$typolinkParameter);
        }
    }
```

**Comment by kszymukowicz** [comment]
Fixed in v1.2.3.
