### ISSUE TITLE
Using in a projekt without composer unpossible?

### ISSUE THREAD

**Issue by olek07** [sourcebroker/t3api#39]
Hi!

The zip-file https://extensions.typo3.org/extension/download/t3api/1.2.1/zip is shipped without dependencies. The vendor folder is absent. How were it possible to use the extension in a T3 8.7 project, that was installed WITHOUT composer?

**Comment by klamparski** [comment]
@olek07 We do not plan to support installation without composer but you can create a fork with all the vendors inside extension. Here is an example: https://github.com/sourcebroker/t3api/issues/15#issuecomment-715894988
