### ISSUE TITLE
Class Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory does not exist. Reflection failed in TYPO3 v 10.4.16

### ISSUE THREAD

**Issue by sathish-programmer** [sourcebroker/t3api#52]
I used to install t3api manually , after install it shows error called 'UnknownClassException'

**Comment by klamparski** [comment]
By default t3api works only in composer based projects. Please check out this discussion: https://github.com/sourcebroker/t3api/discussions/40
