### ISSUE TITLE
TCA configuration "sortby" has no effect for tt_content related items

### ISSUE THREAD

**Issue by Moongazer** [sourcebroker/t3api#65]
There is a strange issue if we create custom content-elements (based on `tt_content`) where child-items having an own relation table. Also the TCA config for these child-items has `'sortby' => 'sorting'` set, the given sort-by column is ignored and the output is sorted by UID (default behavior). Custom entities with child-items are not effected, which is really strange.

I created a demonstration to show the issue (it's a fork of [t3apicontent](https://github.com/klamparski/t3apicontent), the code is on branch `issue/content-sorting`).

## Install / Preparation
1) Start the [t3apidemo](https://github.com/sourcebroker/t3apidemo) (with clean default database)
2) Add the [t3apicontent extension](https://github.com/Moongazer/t3apicontent/tree/issue/content-sorting) of my fork-repository to the `composer.json` of t3apidemo and checkout the branch `issue/content-sorting`:
```
{
  "config": {
    "preferred-install": {
      "moongazer/t3apicontent": "source"
    },
  },
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/Moongazer/t3apicontent.git"
    }
  ],
  "require": {
    "moongazer/t3apicontent": "dev-master"
  },
}
```
3) Import the SQL which you will find inside the [README](https://github.com/Moongazer/t3apicontent/tree/issue/content-sorting#branch-issuecontent-sorting)

## Issue
Browse to `https://t3apidemo.ddev.site:444/_api/content/pages/8` which will respond the following structure (see the items array where the elements are sorted by their UID 1, 2 and 3):
![t3apicontent1](https://user-images.githubusercontent.com/1685510/166110642-a3a20bc1-0f08-4a75-8071-bf2ed0e6359c.png)

In the backend the elements are sorted into a certain order:
![t3apicontent2](https://user-images.githubusercontent.com/1685510/166110704-087fac6f-2a6b-4fcc-8d94-3115d8554de0.png)

**Comment by klamparski** [comment]
Hi @Moongazer.

First of all I need to notice that it's absolutely not up to t3api. Mapping is done completely by Extbase so you would have exactly the same result when dumping it in t3api context or e.g. in Extbase's plugin context.

And the answer for your question is `foreign_sortby` in TCA configuration for `inline` type of column: [foreign_sortby](https://docs.typo3.org/m/typo3/reference-tca/10.4/en-us/ColumnsConfig/Type/Inline.html#foreign-sortby)

Adding it as on screen below to the `Configuration/TCA/Overrides/tt_content.php` resolves the issue.

![image](https://user-images.githubusercontent.com/753410/167359957-106dee6d-7438-4193-9555-8f1d13b93001.png)

**Comment by Moongazer** [comment]
Oh damn, how could I have missed that! Hours of debugging and preparing a show-case example for such a stupid mistake.... sorry about that, and thanks for pointing it out.
