### ISSUE TITLE
CurrentFeUserSubscriber throws access array offset in PHP 8

### ISSUE THREAD

**Issue by Moongazer** [sourcebroker/t3api#71]
If no user-session is available, the `$GLOBALS['TSFE']->fe_user->user` attribute is null, so the array access does not work:
```
PHP Warning: Trying to access array offset on value of type null in /var/www/html/public/typo3conf/ext/t3api/Classes/Serializer/Subscriber/CurrentFeUserSubscriber.php line 59
```
**Fix in [line 59](https://github.com/sourcebroker/t3api/blob/1eaf1119b6c708b4f826dde0378686e4a3b0faae/Classes/Serializer/Subscriber/CurrentFeUserSubscriber.php#L59)**
```
$data[$propertyName] = $GLOBALS['TSFE']->fe_user->user['uid'] ?? null;
```

**Patch-File:**
```
--- Classes/Serializer/Subscriber/CurrentFeUserSubscriber.php
+++ Classes/Serializer/Subscriber/CurrentFeUserSubscriber.php
@@ -56,7 +56,7 @@
                 continue;
             }
 
-            $data[$propertyName] = $GLOBALS['TSFE']->fe_user->user['uid'];
+            $data[$propertyName] = $GLOBALS['TSFE']->fe_user->user['uid'] ?? null;
         }
 
         $event->setData($data);

```

**System:**
TYPO3: v11.5.25
PHP: v8.0
T3API: v2.0.1

**Comment by klamparski** [comment]
Thank you @Moongazer. Currently fix is applied in branch `release/2.1` and will be included in release 2.1.
