### ISSUE TITLE
Add compatibility for TYPO3 12 into t3api core

### ISSUE THREAD

**Issue by kszymukowicz** [sourcebroker/t3api#85]
TYPO3 12 API can be tested on https://github.com/sourcebroker/t3api/tree/release/3.0.0

**Comment by maikschneider** [comment]
Hey, thanks for the work! On first sight, there are some errors I addressed in #87. After applying these, the acceptance tests for one project pass. We have another v11 project with way more detailed API tests, that I'll try to run against this version as well.

We updated the extension some months ago in [this fork](https://github.com/maikschneider/t3api) (I forgot to tell you). Maybe there are some adjustments that you can make use of.

**Comment by crws** [comment]
Hi, after updating a project to TYPO3 12.4.14 I am getting exceptions from those parts of the t3api code that try to set something like   
`$resolver->expressionLanguageVariables['t3apiOperation'] = $operation;` or 
`$this->expressionLanguageVariables[$name] = $value;`



> "Cannot access private property TYPO3\CMS\Core\ExpressionLanguage\Resolver::$expressionLanguageVariables"



In TYPO3 10 and  TYPO3 11, that property was public in the core class.

But with version 12 it has been made private. 

as a temporary fix it does work to just copy the Resolver class into the extension and change the property to public again.

**Comment by fsuter** [comment]
Thanks for all the work on this. Are you planning on making an official release?

**Comment by fsuter** [comment]
Wonderful! Great news and thanks for all your work.
