### ISSUE TITLE
Implement support for CORS

### ISSUE THREAD

**Issue by klamparski** [sourcebroker/t3api#9]
- [x] Make CORS configurable
- [x] Add support for preflight request

This feature should be started with changes already done on `issue-7` branch. It contains a huge refactor of AbstractDispatcher which will be soon merged to master branch.

**Comment by okroener** [comment]
@klamparski I have noticed that CORS had to be configured manually right now.

I have changed the **.htaccess** file and added the following lines as well as I have added a **blank.html** to bypass the preflight request.

`RewriteCond %{REQUEST_METHOD} OPTIONS`
`RewriteRule ^(.*)$ blank.html [QSA,L]`

`Header set Access-Control-Allow-Origin "*"`
`Header set Access-Control-Allow-Methods "*"`
`Header set Access-Control-Allow-Headers "content-type, access"`
`Header set Access-Control-Max-Age "86400"`

This is working so far as long as it is implemented in the component itself.

Thanks for your great work!

**Comment by klamparski** [comment]
@okroener Thanks. Nice idea for temporary solution. As far as i know @kryslin already implemented configurable CORS support on branch `issue-9` but we are not ready with documentation yet. We will keep you updated within this issue when it is ready and merged to master branch.

**Comment by Moongazer** [comment]
@kryslin are there any plans or a schedule to merge CORS in the near/midterm future? As far as I can see most of it is done (except for v10 I had to fix few things to make it work, see https://github.com/sourcebroker/t3api/pull/18).

The workaround of @okroener works great for the dev system, but we don't feel well to apply such a hack in a production environment. In our case, a standalone front-end app is developed using SSR, therefore running under an own domain where CORS comes into play.

Some people say CORS config should only be applied on webserver level. I'm lacking detailed experience here what is right and which layer (Webserver/PHP/TYPO3) should set the correct response-headers. If anyone of you has expert knowledge about common best-practice related to this, any feedback would be appreciated.

**Comment by klamparski** [comment]
@okroener @Moongazer Took some time but it's [finally done](https://github.com/sourcebroker/t3api/pull/28). If you are still interested in it you can, you can find [documentation here](https://docs.typo3.org/p/sourcebroker/t3api/master/en-us/Cors/Index.html).
